import { StyleSheet } from "react-native";

export const stylesEventPresentation = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    cardImage: {
        width: 320,
        height: 192,
        backgroundColor: '#FFFFFF',
        marginRight: 15,
        marginLeft:15,
        marginTop: 15,
        position:'relative',
        marginBottom: 10,
    },
    cardCover : {
        elevation: 4
    },
    imageOverlay: {
        position: 'absolute', 
        bottom: 10,
        left: 10, 
        backgroundColor: 'rgba(128, 128, 128, 0.5)', 
        paddingVertical: 5, 
        paddingHorizontal: 10, 
        borderRadius: 5, 
        flexDirection: 'row', 
        alignItems: 'center', 
    },
    overlayText: {
        color: '#FFF', 
        fontSize: 12, 
        fontWeight: '600', 
        fontFamily: 'Inter', 
        marginLeft: 5, 
    },       
    titleEventContainer : {
        width: 320,
        height: 29,
        flexDirection: 'row', 
        alignItems: 'flex-start', 
        marginTop: 0,
        marginRight: 15,
        marginLeft:15,
        marginBottom:5,
    },
    titleEventText : {
        color: '#4B0082',
        width:'80%',
        fontFamily: 'Inter',
        fontWeight: '700',
        fontSize: 20,
        marginTop:0
    },
    containerUser: {
        borderColor: '#C497E5',
        borderWidth: 1,
        width: 170,
        height: 45,
        borderRadius: 25,
        marginTop: 10,
        marginBottom: 10,
        marginLeft: 20,
        backgroundColor: '#FFF',
        paddingHorizontal: 10,
        alignSelf:'left',
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentWrapper: {
        flexDirection: 'row', 
        alignItems: 'center', 
        width: '100%',
        justifyContent: 'space-between', 
    },
    textUser: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#333',
        flex: 1, 
        textAlign: 'center',
    },
    containerDetails: {
        width: 320,
        height: 110,
        backgroundColor: '#FFFFFF',
        borderColor: '#C497E5',
        borderWidth: 1,
        marginRight: 15,
        marginLeft: 15,
        marginTop: 15,
        position: 'relative',
        marginBottom: 10,
        padding: 10, 
        borderRadius: 15,
        elevation: 4, 
    },
    rowContainer: {
        flexDirection: 'row', 
        alignItems: 'center', 
        marginVertical: 5, 
    },
    textItem: {
        marginLeft: 10, 
        fontSize: 14,
        fontWeight: '400',
        color: '#333', 
        flex: 1, 
    },
    topRightContainer: {
        position: 'absolute', 
        top: 0, 
        right: 0,
        flexDirection: 'row', 
        alignItems: 'center', 
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        padding: 5,
    },
    topRightText: {
        marginLeft: 5,
        fontSize: 14,
        fontWeight: 'Regular',
        color: 'black',
    },
    bottomRightContainer: {
        position: 'absolute',
        bottom: 0, 
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        padding: 5,
    },
    bottomRightText: {
        marginLeft: 5,
        fontSize: 16,
        fontWeight: 'Regular',
        color: 'black',
    },
    containerAboutEvent: {
        width: 320,
        backgroundColor: '#FFFFFF',
        borderColor: '#C497E5',
        borderWidth: 1,
        marginRight: 15,
        marginLeft: 15,
        marginBottom: 10,
        padding: 10, 
        borderRadius: 15,
        elevation: 4, 
        alignItems: 'flex-start',  
        justifyContent: 'flex-start', 
        minHeight: 60,
        maxHeight: 300, 
        overflow: 'hidden', 
    },
    textDescription: {
        fontSize: 14, 
        fontWeight: '400', 
        color: '#333',
        lineHeight: 20, 
        flexWrap: 'wrap',  
    },
    textNoDescription: {
        fontSize: 14,
        fontWeight: '400',
        color: 'gray',
        lineHeight: 20,
        flexWrap: 'wrap',
        fontStyle: 'italic', 
    },   
    containerButton: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row', 
        width: '100%', 
        marginBottom: 20,
        marginTop:10,
    },
    roundButton: {
        width: 60, 
        height: 60,
        borderRadius: 30, 
        backgroundColor: 'white',
        borderColor: '#C497E5',
        borderWidth:1,
        justifyContent: 'center', 
        alignItems: 'center', 
        marginRight: 20, 
        elevation: 5,
    },
    rectangleButton: {
        width: 200, 
        height: 45, 
        backgroundColor: 'white',
        borderColor: '#C497E5',
        borderWidth:1,
        justifyContent: 'center', 
        alignItems: 'center', 
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#C497E5',
        elevation: 5,
        borderRadius: 20
    },
    rectangleButtonText: {
        color: '#4B0082',
        fontSize: 25, 
        fontWeight: '700', 
        textAlign: 'center',
    },
    icon: {
        alignSelf: 'center', 
    },
    fixedButtonContainer: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
        paddingVertical: 10,
    },
});